# Useful when 'connector' is set to 'slurmrest'; not implemented yet
slurmrest:
  url: "http+unix:///default?socket=/tmp/slurmrestd.sock"

slurmer:
  ip: 127.0.0.1
  port: 8080
  connector: slurmcli
  working_dir: /var/lib/slurmer
  templates_dir: /etc/slurmer/templates
  executor_path: /usr/bin/executor
  applications:
    - name: app1
      token: averycomplicatedchallenge
      uuid: a9a5fc66-9bed-4a13-874a-d8d7d1756224 # a random app uuid
  logs:
    # available: text, json
    format: text

    stdout: false
    output: /var/logs/slurmer.log

    # available, from most to less verbose:
    # trace, debug, info, warning, error, fatal, panic
    level: debug

# To enable OIDC
oidc:
  enabled: false
  issuer: ""
  audience: ""
