slurmrest:
  url: "http+unix:///default?socket=/tmp/slurmrestd.sock"

slurmer:
  ip: 127.0.0.1
  port: 8080
  connector: slurmcli
  working_dir: /tmp/slurmer
  templates_dir: configs/templates
  applications:
    - name: app1
      token: test
      uuid: a9a5fc66-9bed-4a13-874a-d8d7d1756224
  logs:
    # available: text, json
    format: text

    stdout: false
    output: logs/slurmer.txt

    # available, from most to less verbose:
    # trace, debug, info, warning, error, fatal, panic
    level: debug
