@baseUrl = http://{{host}}:{{port}}
@job = ff064d2f-28e1-4e45-9113-ddfaedad7f36

###
GET {{baseUrl}}/apps
Accept: application/json
X-Auth-Token: {{token}}

###
GET {{baseUrl}}/apps/{{app}}
Accept: application/json
X-Auth-Token: {{token}}

###
GET {{baseUrl}}/apps/{{app}}/jobs
Accept: application/json
X-Auth-Token: {{token}}

###
POST {{baseUrl}}/apps/{{app}}/jobs
Accept: application/json
X-Auth-Token: {{token}}
Content-Type: application/json

{
  "job_name": "test_job",
  "cpus_per_task": 1,
  "command": "echo",
  "args": ["hello", ",", "world"]
}

###
PUT {{baseUrl}}/apps/{{app}}/jobs/{{job}}/status
Accept: application/json
X-Auth-Token: {{token}}
Content-Type: application/json

"started"

###
PUT {{baseUrl}}/apps/{{app}}/jobs/{{job}}/status
Accept: application/json
X-Auth-Token: {{token}}
Content-Type: application/json

"stopped"

###
GET {{baseUrl}}/apps/{{app}}/jobs/{{job}}
Accept: application/json
X-Auth-Token: {{token}}

###
GET {{baseUrl}}/apps/{{app}}/jobs/{{job}}/files
Accept: application/zip
X-Auth-Token: {{token}}

### Sends to the job the archive `test.zip` and unzip it in its directory
POST {{baseUrl}}/apps/{{app}}/jobs/{{job}}/files
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
X-Auth-Token: {{token}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="job_dir"; filename="test.zip"
Content-Type: application/zip

< ./test.zip
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
GET {{baseUrl}}/apps/{{app}}/jobs/{{job}}/batch
X-Auth-Token: {{token}}

###
GET {{baseUrl}}/apps/{{app}}/jobs/{{job}}/out
X-Auth-Token: {{token}}

###
DELETE {{baseUrl}}/apps/{{app}}/jobs/{{job}}
X-Auth-Token: {{token}}

###
PATCH {{baseUrl}}/apps/{{app}}/jobs/{{job}}
X-Auth-Token: {{token}}

{
  "action": "prune"
}

###
PATCH {{baseUrl}}/apps/{{app}}/jobs/{{job}}
X-Auth-Token: {{token}}

{
  "action": "start"
}

###
PATCH {{baseUrl}}/apps/{{app}}/jobs/{{job}}
X-Auth-Token: {{token}}

{
  "action": "stop"
}
