@hostname = 127.0.0.1
@port = 8080
@host = {{hostname}}:{{port}}
@token = debug
@app = debug
@job = debug


GET http://{{host}}/apps
Accept: application/json
X-Auth-Token: {{token}}

###
GET http://{{host}}/apps/{{app}}
Accept: application/json
X-Auth-Token: {{token}}

###
GET http://{{host}}/apps/{{app}}/jobs
Accept: application/json
X-Auth-Token: {{token}}

###
POST http://{{host}}/apps/{{app}}/jobs
Accept: application/json
X-Auth-Token: {{token}}
Content-Type: application/json

{
  "job_name": "test_job",
  "cpus_per_task": 1
}

###
PUT http://{{host}}/apps/{{app}}/jobs/{{job}}/status
Accept: application/json
X-Auth-Token: {{token}}
Content-Type: application/json

"started"

###
PUT http://{{host}}/apps/{{app}}/jobs/{{job}}/status
Accept: application/json
X-Auth-Token: {{token}}
Content-Type: application/json

"stopped"

###
GET http://{{host}}/apps/{{app}}/jobs/{{job}}
Accept: application/json
X-Auth-Token: {{token}}

###
GET http://{{host}}/apps/{{app}}/jobs/{{job}}/files
Accept: application/zip
X-Auth-Token: {{token}}

###
POST http://{{host}}/apps/{{app}}/jobs/{{job}}/files
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
X-Auth-Token: {{token}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="job_dir"; filename="test.zip"
Content-Type: application/zip

< ./test.zip
------WebKitFormBoundary7MA4YWxkTrZu0gW--